name: code-quality
on: [push]
jobs:
  run-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # ! Keep version in phase with the version defined in <root>/.nvmrc !
          node-version: 14.17
      - name: Install yarn
        run: npm i -g yarn
      - name: Install packages
        run: yarn
      - name: Check linting
        run: yarn run lint
